### ISSUE TITLE
403 Forbidden while downloading from packages from yum repo

### ISSUE THREAD

**Issue by triggerants** [asteris-llc/mantl-packaging#139]
while enabling mantl-1.3 repo on centos, I get the below error
https://dl.bintray.com/shippedrepos/mantl-1.3/repodata/repomd.xml
HTTPS Error 403 - Forbidden Trying other mirror.

**Comment by Theaxiom** [comment]
It seems that Cisco closed all the repos for Mantl from bintray. You can get the updated packages here: https://github.com/mantl/mantl/wiki/Notes

So you would change all the corresponding references to the following:

- https://bintray.com/mantl/rpm-packages
- https://dl.bintray.com/mantl/rpm-packages
- https://dl.bintray.com/mantl/rpm-packages/repodata/repomd.xml

**Comment by triggerants** [comment]
The new package repository is working fine. So closing the issue.

**Comment by Theaxiom** [comment]
Thanks!
