### ISSUE TITLE
Update dnsmasq to resolve short hostnames

### ISSUE THREAD

**Issue by stevendborrelli** [asteris-llc/mantl-packaging#43]
Update dnsmasq config to resolve .node.consul addresses so that short hostnames work.

**Comment by josdotso** [comment]
Posting this here, per Gitter convo [1]: 

> On Mantl+Mesos+Marathon, when I start a Docker container, is the Docker daemon configured to set the DNS default search domain to "service.consul"?  With this setup, I could address one container from another by the former's shortname. The SRV stuff will be more involved of course, but shortname is cool when we get to Marathon JSON.

[1] https://gitter.im/CiscoCloud/mantl?at=56d9e6c219834f3c3534e048

**Comment by BrianHicks** [comment]
I'm just a bit concerned about what happens when a service has the same name as a node. It doesn't sound fantastically likely to happen, but if it does which should we prefer?

**Comment by josdotso** [comment]
I thought about that too.  This makes a good case for "node" being the search for the node, but "service" being the Docker daemon default. ` --dns-search=DOMAIN... ` (if I read the Docker docs correctly)

**Comment by stevendborrelli** [comment]
I think the node should come first in search. 

If service  is defined, that means that a user could poison dns by launching a container called `mantl-control-01`.

Maybe we shouldn't allow services to use short names.

**Comment by josdotso** [comment]
Agreed.  Leaving the service search out of the node's search would fix that, but would it be a problem that Docker uses short service names?  I guess they do sometimes call nodes (e.g. Zookeeper).

**Comment by BrianHicks** [comment]
So we're looking at search domains:

1. `.consul`
2. `.node.consul`
3. `.service.consul`

Do we want to include prepared queries in this? I'm leaning toward "no".

**Comment by josdotso** [comment]
Seems to me that .consul as the sole search param makes most sense.  Someone might legitimately have some service with the same name as the node.  Searching .consul only lets the consumer address shorter, but only to the extent that name conflicts don't arise.

**Comment by BrianHicks** [comment]
I implemented this with `node.consul` and `consul`. That way the shortest resolved (IE `x`) will always be a node, if one needs to disambiguate `x.service` vs `x.node` is available.
