### ISSUE TITLE
Add logging and logrotate to traefik

### ISSUE THREAD

**Issue by stevendborrelli** [asteris-llc/mantl-packaging#6]
Access logs can be added: 
- [x] `accessLogsFile = "/var/log/traefik/access.log"`
- [x] `traefikLogsFile = "/var/log/traefik/traefik.log"`
- [x] add logroate.d config for access.log
- [x] update selinux policy to allow traefik to create/update access & error.log

**Comment by sehqlr** [comment]
@stevendborrelli Does the traefik.log file need to be rotated?

**Comment by stevendborrelli** [comment]
Yes.

**Comment by sehqlr** [comment]
I made a PR: #9

**Comment by sehqlr** [comment]
The PR was merged.
