### ISSUE TITLE
mantl-dns: dnsmasq search configuration

### ISSUE THREAD

**Issue by ryane** [asteris-llc/mantl-packaging#84]
see https://github.com/CiscoCloud/mantl/issues/1367 and https://github.com/CiscoCloud/mantl/issues/1377. DNS was not able to resolve aws internal host names. Using the `--domain='#'` option and a single resolv file [1] addressed the problem.

[1] we manually tested by running this:

`cat /etc/resolv.conf.mantl-dns /etc/resolv.conf.mas1 > /etc/resolv.conf`

**Comment by ryane** [comment]
per @BrianHicks, the `--domain='#'` option is not necessary. Just using a single resolv file should be sufficient

**Comment by ChrisAubuchon** [comment]
Does `--domain='#'` (or `domain=#` in `10-consul`) work without combining the resolv.conf files?

**Comment by ryane** [comment]
No, when we tried it we would get errors like `dnsmasq: must have exactly one resolv.conf to read domain from`.

**Comment by ChrisAubuchon** [comment]
Do you happen to have a `resolv.conf` from AWS that you can post here? `domain=#` works fine on GCE. I'm wondering if we're going to need provider-specific DNS configs... (yuck)

**Comment by ryane** [comment]
One way to see the problem is to build an AWS cluster with the `preserve hostname` and `set persistent hostname` tasks commented out: https://github.com/CiscoCloud/mantl/blob/master/roles/common/tasks/main.yml#L21

You'll end up with hostnames like `ip-10-1-1-43`. 

```shell
[centos@ip-10-1-1-43 ~]$ hostname
ip-10-1-1-43.ec2.internal
[centos@ip-10-1-1-43 ~]$ ping ip-10-1-1-43.ec2.internal
PING ip-10-1-1-43.ec2.internal (10.1.1.43) 56(84) bytes of data.
64 bytes from resching-aws-control-01 (10.1.1.43): icmp_seq=1 ttl=64 time=0.022 ms
64 bytes from resching-aws-control-01 (10.1.1.43): icmp_seq=2 ttl=64 time=0.034 ms
^C
--- ip-10-1-1-43.ec2.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.022/0.028/0.034/0.006 ms
[centos@ip-10-1-1-43 ~]$ ping ip-10-1-1-43
ping: unknown host ip-10-1-1-43
[centos@ip-10-1-1-43 ~]$ cat /etc/resolv.conf
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul
nameserver 127.0.0.1
[centos@ip-10-1-1-43 ~]$ cat /etc/resolv.conf.masq
; generated by /usr/sbin/dhclient-script
search ec2.internal
nameserver 10.1.0.2
```

So the search path in `/etc/resolv.conf.masq` (which is included in `/etc/dnsmasq.d/10-consul`) is not being respected. If you append the contents of `/etc/resolv.conf.masq` into `/etc/resolv.conf.mantl-dns`, the search path is respected (event without `domain=#`).

**Comment by ChrisAubuchon** [comment]
After appending `/etc/resolv.conf.masq` to `/etc/resolv.conf.mantl` the `search node.consul consul` line is ignored. The resolver uses the last `search` directive in `/etc/resolv.conf`.

On GCE
```
[root@chris-control-001 etc]# cat /etc/resolv.conf
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul
nameserver 127.0.0.1
# Generated by NetworkManager
search c.asteris-mi.internal. google.internal. c.asteris-mi.internal
nameserver 169.254.169.254
root@chris-control-001 etc]# ping chris-control-002.node
ping: unknown host chris-control-002.node
[root@chris-control-001 etc]# ping consul.service
ping: unknown host consul.service
[root@chris-control-001 etc]# ping consul.service.consul
PING consul.service.consul (10.0.0.2) 56(84) bytes of data.
64 bytes from chris-control-001.c.asteris-mi.internal (10.0.0.2): icmp_seq=1 ttl=64 time=0.026 ms
```

Can you confirm the same behavior on AWS? If it behaves the same then the `search node.consul consul` directive is being ignored and we need to figure something else out...

**Comment by ryane** [comment]
confirmed. same problem on AWS:

```
# ping resching-aws-control-01.node
ping: unknown host resching-aws-control-01.node
```

**Comment by ChrisAubuchon** [comment]
I think we're going to have to find something that parses the resolv.conf files and combine the search directives. Might have to write a simple parser ourselves. This `/etc/resolv.conf` seems to work:
```
# this config installed by mantl-dns

# search is added here so that the system can address nodes by their simplest
# name (x.node.consul becomes x.node or simply x.) This will work for service
# addressing as well, so you can use y.service instead of y.service.consul
options ndots:2
search node.consul consul c.asteris-mi.internal. google.internal. c.asteris-mi.internal
nameserver 127.0.0.1
nameserver 169.254.169.254
```

**Comment by ryane** [comment]
we actually used to do that in ansible pre mantl-dns:

https://github.com/CiscoCloud/mantl/blob/1.0.3/roles/dnsmasq/tasks/main.yml#L22
https://github.com/CiscoCloud/mantl/blob/1.0.3/roles/dnsmasq/templates/resolv.conf.j2#L1
